# -*- coding: utf-8 -*-  # Specifies the file encoding as UTF-8 so that Chinese displays correctly
"""
Compute the total carbon debt of wind power (merging biomass, soil and manufacturing carbon)  # Describes the purpose of this script
Author: 锐多宝 (ruiduobao)  # Author information
Date: 2026-01-27  # Date

Function overview:  # Module function description
1) Read the three wind carbon loss result tables (biomass, soil, manufacturing) CSV and merge them based on fid  # Data source and merge key description
2) Unify units and handle missing values (tC -> tCO2e conversion factor 3.67)  # Unit conversion description
3) Compute the total carbon debt Total_Debt_tCO2 and output it to the specified directory  # Total computation and output
4) Write a detailed run log for convenient in-directory review when terminal output is large  # Log description
"""  # End of docstring

import os  # File and directory operations
import pandas as pd  # Tabular data processing
from datetime import datetime  # Timestamps for logging

# ================= Configuration section =================  # Start of configuration section

# Input file base paths (provided by the user and generated by other scripts)
BASE_SOIL_DIR = r"Z:\Mywork\论文\全球绿色能源生态评估_2025.12.24\制图\4.1.2风电土壤碳损失"
BASE_BIO_DIR = r"Z:\Mywork\论文\全球绿色能源生态评估_2025.12.24\制图\4.2.2风电生物碳损失"
BASE_MFG_DIR = r"Z:\Mywork\论文\全球绿色能源生态评估_2025.12.24\制图\4.3.2风电制造碳损失"

# Output base directory (merged total carbon debt)
BASE_OUTPUT_DIR = r"Z:\Mywork\论文\全球绿色能源生态评估_2025.12.24\制图\4.4.2风机碳债务合并损失"

# Constant: carbon to carbon dioxide conversion factor  # Conversion factor description
CO2_FACTOR = 3.67  # 1 tC = 3.67 tCO2e

# ================= Utility functions =================  # Start of utility functions

def ensure_dir(path):  # Directory creation function
    if not os.path.exists(path):  # If the directory does not exist
        os.makedirs(path)  # Create the directory

def log_message(msg, log_file=None):  # Logging function
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # Current time string
    line = f"[{ts}] {msg}"  # Compose the log content
    print(line)  # Print to the terminal
    if log_file:
        with open(log_file, "a", encoding="utf-8") as f:  # Append to the log file
            f.write(line + "\n")  # Write one log line

def safe_read_csv(path, name, log_file=None):  # Safely read a CSV and log
    if not os.path.exists(path):  # Check whether the file exists
        log_message(f"Error: {name} file not found: {path}", log_file)  # Log the error
        return pd.DataFrame()  # Return an empty DataFrame
    try:  # Try to read
        df = pd.read_csv(path)  # Read the CSV
        log_message(f"{name} loaded; records: {len(df)}", log_file)  # Log the successful read and record count
        return df  # Return the DataFrame
    except Exception as e:  # Catch exceptions
        log_message(f"Error: failed to read {name}: {e}", log_file)  # Log the error message
        return pd.DataFrame()  # Return an empty DataFrame

def standardize_keys(df, fid_col_candidates):  # Standardize the merge key fid
    for c in fid_col_candidates:  # Iterate over candidate column names
        if c in df.columns:  # If the column exists
            df = df.rename(columns={c: "fid"})  # Rename to fid
            break  # Break after finding
    if "fid" in df.columns:  # If fid exists
        df["fid"] = pd.to_numeric(df["fid"], errors="coerce").astype("Int64")  # Convert to integer allowing NA
    return df  # Return the processed DataFrame

def extract_year(df):  # Extract a unified installation year column installation_year
    if "installation_year" in df.columns:  # installation_year already exists
        return df["installation_year"]  # Return it directly
    if "year" in df.columns:  # If year exists
        return pd.to_numeric(df["year"], errors="coerce")  # Convert to numeric and return
    if "constructi" in df.columns:  # If constructi exists
        return pd.to_numeric(df["constructi"], errors="coerce")  # Convert to numeric and return
    return pd.Series(dtype="float64")  # Return an empty column by default

def extract_country(df):  # Unify the country field country_final
    if "country_final" in df.columns:  # If the final country column already exists
        return df["country_final"]  # Return that column
    if "country" in df.columns:  # If country exists
        return df["country"].fillna("Unknown")  # Fill missing and return
    if "COUNTRY" in df.columns:  # If the shapefile-style COUNTRY column exists
        return df["COUNTRY"].fillna("Unknown")  # Fill missing and return
    return pd.Series(["Unknown"] * len(df))  # Return all Unknown

# ================= Business logic =================  # Start of the main logic

def process_scenario(scenario_name):
    """
    Process the wind carbon loss merge for a single scenario
    """
    print(f"\n>>> Processing scenario: {scenario_name}")
    
    # Build paths
    soil_csv = os.path.join(BASE_SOIL_DIR, scenario_name, "Wind_Soil_Loss_Result.csv")
    bio_csv = os.path.join(BASE_BIO_DIR, scenario_name, "Wind_Biomass_Loss_Result.csv")
    mfg_csv = os.path.join(BASE_MFG_DIR, scenario_name, "Wind_Manufacturing_Carbon_Result.csv")
    
    output_dir = os.path.join(BASE_OUTPUT_DIR, scenario_name)
    output_csv = os.path.join(output_dir, "Wind_Total_Carbon_Debt_Result.csv")
    log_file = os.path.join(output_dir, "Wind_Total_Carbon_Debt_Merge_Log.txt")
    
    ensure_dir(output_dir)
    if os.path.exists(log_file):
        os.remove(log_file)
        
    log_message(f"Scenario: {scenario_name}", log_file)
    log_message(">>> Starting to merge wind carbon losses (biomass/soil/manufacturing)", log_file)

    # 1) Read the three data tables
    df_soil = safe_read_csv(soil_csv, "soil carbon loss", log_file)
    df_bio = safe_read_csv(bio_csv, "biomass carbon loss", log_file)
    df_mfg = safe_read_csv(mfg_csv, "manufacturing carbon loss", log_file)

    # 2) Standardize keys and key columns
    df_soil = standardize_keys(df_soil, ["fid", "FID"])
    df_bio = standardize_keys(df_bio, ["fid", "FID"])
    df_mfg = standardize_keys(df_mfg, ["fid", "FID"])

    if df_soil.empty and df_bio.empty and df_mfg.empty:
        log_message("Error: all three input tables are empty; aborting the merge.", log_file)
        return

    # 3) Select the needed fields and perform unit conversion
    if "Loss_Soil_tCO2" not in df_soil.columns and "Loss_Soil_tC" in df_soil.columns:
        df_soil["Loss_Soil_tCO2"] = pd.to_numeric(df_soil["Loss_Soil_tC"], errors="coerce").fillna(0) * CO2_FACTOR
    
    if "Loss_Bio_tCO2" not in df_bio.columns and "Loss_Bio_tC" in df_bio.columns:
        df_bio["Loss_Bio_tCO2"] = pd.to_numeric(df_bio["Loss_Bio_tC"], errors="coerce").fillna(0) * CO2_FACTOR

    # Installation year and country fields
    df_soil["installation_year_tmp"] = extract_year(df_soil)
    df_bio["installation_year_tmp"] = extract_year(df_bio)
    df_mfg["installation_year_tmp"] = extract_year(df_mfg)

    df_soil["country_tmp"] = extract_country(df_soil)
    df_bio["country_tmp"] = extract_country(df_bio)
    df_mfg["country_tmp"] = extract_country(df_mfg)

    # 4) Merge step by step
    log_message("Starting the outer join merge...", log_file)
    df_merge = pd.merge(df_soil[["fid", "Loss_Soil_tCO2", "installation_year_tmp", "country_tmp"]],
                        df_bio[["fid", "Loss_Bio_tCO2", "installation_year_tmp", "country_tmp"]],
                        on="fid", how="outer", suffixes=("_soil", "_bio"))
    df_merge = pd.merge(df_merge,
                        df_mfg[["fid", "Loss_Mfg_tCO2", "installation_year_tmp", "country_tmp"]],
                        on="fid", how="outer")

    # 5) Fill missing values and unify year/country
    for col in ["Loss_Soil_tCO2", "Loss_Bio_tCO2", "Loss_Mfg_tCO2"]:
        if col not in df_merge.columns:
            df_merge[col] = 0.0
        df_merge[col] = pd.to_numeric(df_merge[col], errors="coerce").fillna(0.0)

    # Unify the installation year
    df_merge["installation_year"] = df_merge["installation_year_tmp"].copy()
    df_merge["installation_year"] = df_merge["installation_year"].fillna(df_merge.get("installation_year_tmp_bio"))
    df_merge["installation_year"] = df_merge["installation_year"].fillna(df_merge.get("installation_year_tmp_soil"))
    df_merge["installation_year"] = pd.to_numeric(df_merge["installation_year"], errors="coerce")
    df_merge["installation_year"] = df_merge["installation_year"].fillna(2017).astype(int)

    # Unify the country
    df_merge["country_final"] = df_merge["country_tmp"].copy()
    df_merge["country_final"] = df_merge["country_final"].fillna(df_merge.get("country_tmp_bio"))
    df_merge["country_final"] = df_merge["country_final"].fillna(df_merge.get("country_tmp_soil"))
    df_merge["country_final"] = df_merge["country_final"].fillna("Unknown")

    # 6) Compute the total carbon debt
    df_merge["Total_Debt_tCO2"] = (df_merge["Loss_Soil_tCO2"] + df_merge["Loss_Bio_tCO2"] + df_merge["Loss_Mfg_tCO2"]).astype(float)

    # 7) Organize the output columns and save
    out_cols = ["fid", "installation_year", "country_final", "Loss_Bio_tCO2", "Loss_Soil_tCO2", "Loss_Mfg_tCO2", "Total_Debt_tCO2"]
    df_out = df_merge[out_cols].copy()
    df_out.to_csv(output_csv, index=False, encoding="utf-8-sig")
    log_message(f"Merge complete; output file: {output_csv}", log_file)

    # 8) Write the summary statistics to the log
    total_mt = df_out["Total_Debt_tCO2"].sum() / 1e6
    log_message(f"{scenario_name} - Global wind total carbon debt: {total_mt:.4f} MtCO2e", log_file)
    
    by_year = df_out.groupby("installation_year")["Total_Debt_tCO2"].sum() / 1e6
    log_message("Annual total carbon debt (MtCO2e):", log_file)
    for y, v in by_year.items():
        log_message(f"  - {y}: {v:.4f}", log_file)
        
    by_country = df_out.groupby("country_final")["Total_Debt_tCO2"].sum().sort_values(ascending=False).head(10) / 1e6
    log_message("Top 10 countries total carbon debt (MtCO2e):", log_file)
    for c, v in by_country.items():
        log_message(f"  - {c}: {v:.4f}", log_file)

def main():
    scenarios = ["乐观场景", "标准场景", "悲观场景"]
    for scenario in scenarios:
        process_scenario(scenario)

if __name__ == "__main__":
    main()
