"""
Wind Carbon Debt Statistical Analysis (2017 onwards)  # Describes the purpose of this script for wind power statistics
Author: 锐多宝 (ruiduobao)  # Author information
Date: 2026-01-27  # Date

Function:  # Overview of functions
1. Read the merged wind total carbon debt result table (generated by "2.1.风电总的碳损失.py")  # Data source description
2. Filter wind farm sites installed in 2017 and later for statistics  # Year filter description
3. Compute totals, country ranking, annual trend, component contribution and distribution characteristics  # Metric description
4. Output figures and corresponding data tables to the specified directory, and write a run log  # Output and log description
5. Map distribution and latitude-band analysis (based on wind turbine buffer vector centroids)  # Spatial analysis description
6. Technology-carbon intensity relationship scatter plot (Rated Power vs Debt Intensity)  # Technical relationship figure description
"""

import os  # File path operations
import pandas as pd  # Tabular data processing
import numpy as np  # Numerical computation
import matplotlib.pyplot as plt  # Plotting
import seaborn as sns  # Statistical plotting
from datetime import datetime  # Timestamps
import geopandas as gpd  # Map plotting
from matplotlib.colors import LogNorm  # Log color scale

# ================= Configuration =================  # Start of configuration section

BASE_INPUT_DIR = r"Z:\Mywork\论文\全球绿色能源生态评估_2025.12.24\制图\4.4.2风机碳债务合并损失"  # Base input directory for wind total carbon debt
WIND_SHP_PATH = r"Z:\Mywork\论文\全球绿色能源生态评估_2025.12.24\数据\风机缓冲区\风机80米缓冲区.shp"  # Wind turbine buffer vector, used to obtain coordinates and country
BASE_MFG_DIR = r"Z:\Mywork\论文\全球绿色能源生态评估_2025.12.24\制图\4.3.1风电制造碳损失"  # Base directory of manufacturing carbon results, used for Rated_Power

try:
    WORLD_SHP = gpd.datasets.get_path('naturalearth_lowres')  # World vector
except Exception:
    WORLD_SHP = r"Z:\Mywork\论文\全球绿色能源生态评估_2025.12.24\制图\3.发电潜力计算\ne_110m_admin_0_countries\ne_110m_admin_0_countries.shp"  # Fallback

START_YEAR = 2017  # Starting year for statistics
END_YEAR = 2024  # Ending year for statistics

# Plot style settings
sns.set_theme(style="ticks", font="Arial", context="paper")  # Set seaborn style
plt.rcParams["figure.dpi"] = 300  # Figure resolution
plt.rcParams["savefig.dpi"] = 300  # Save resolution
plt.rcParams["axes.grid"] = True  # Show grid
plt.rcParams["grid.alpha"] = 0.3  # Grid transparency
plt.rcParams["font.sans-serif"] = ["Arial", "SimHei"]  # Font settings
plt.rcParams["axes.unicode_minus"] = False  # Display minus sign

# ================= Utility functions =================

def ensure_dir(path):  # Create directory
    if not os.path.exists(path):  # Check whether the directory exists
        os.makedirs(path)  # Create directory

def log_message(message, log_path=None):  # Write log
    time_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # Current time
    full_message = f"[{time_str}] {message}"  # Compose log message
    print(full_message)  # Print to terminal
    if log_path:
        with open(log_path, "a", encoding="utf-8") as f:  # Open log file
            f.write(full_message + "\n")  # Write log

def export_plot_data(df, filename, output_dir, log_path=None):  # Export chart data
    csv_path = os.path.join(output_dir, filename.replace(".png", ".csv"))  # Output path
    df.to_csv(csv_path, index=True, encoding="utf-8-sig")  # Save CSV
    log_message(f"Chart data exported: {csv_path}", log_path)  # Record export info

def check_required_columns(df, cols, table_name, log_path=None):  # Check required columns
    missing = [c for c in cols if c not in df.columns]  # List of missing columns
    if missing:  # If any missing
        log_message(f"{table_name} missing columns: {missing}", log_path)  # Output log
        return False  # Return failure
    return True  # Return success

# ================= Data loading =================

def load_data(input_csv, log_path=None):  # Load wind total carbon debt data
    if not os.path.exists(input_csv):  # Check whether the input file exists
        log_message(f"Error: input file not found: {input_csv}", log_path)  # Output error
        return None  # Return None
    df = pd.read_csv(input_csv)  # Read input table
    log_message(f"Loaded data records: {len(df)}", log_path)  # Output record count
    required_ok = check_required_columns(df, ["fid", "Total_Debt_tCO2"], "Total carbon debt table", log_path)  # Check required columns
    if not required_ok:  # If required columns are missing
        return None  # Return None
    if "installation_year" not in df.columns and "year" in df.columns:  # If installation_year is missing
        df["installation_year"] = df["year"]  # Use year as a substitute
    if "installation_year" not in df.columns:  # If the year column still does not exist
        log_message("Error: missing installation_year/year field; cannot filter by year", log_path)  # Output error
        return None  # Return None
    df["installation_year"] = pd.to_numeric(df["installation_year"], errors="coerce")  # Convert to numeric
    df = df[df["installation_year"].notna()].copy()  # Drop records without year
    df["installation_year"] = df["installation_year"].astype(int)  # Convert to integer
    return df  # Return data

def load_shp_centroids(log_path=None):  # Load wind turbine buffer vector and compute centroid coordinates
    if not os.path.exists(WIND_SHP_PATH):  # Check whether the file exists
        log_message(f"Warning: wind turbine vector not found: {WIND_SHP_PATH}. Spatial distribution and latitude bands will be skipped.", log_path)  # Output warning
        return None  # Return None
    try:  # Try to read the vector
        gdf = gpd.read_file(WIND_SHP_PATH)  # Read vector
    except Exception as e:  # Read failed
        log_message(f"Failed to read wind turbine vector: {e}", log_path)  # Record error
        return None  # Return None
    # Standardize the fid column  # Column unification
    if "fid_1" in gdf.columns:  # If fid_1 exists
        gdf = gdf.rename(columns={"fid_1": "fid"})  # Rename to fid
    if "fid" not in gdf.columns:  # If fid still missing
        gdf["fid"] = gdf.index  # Use index as fid
    gdf["fid"] = pd.to_numeric(gdf["fid"], errors="coerce").astype("Int64")  # Convert to integer
    # Compute centroid coordinates  # Centroid computation
    try:  # Try to compute centroids
        gdf = gdf.to_crs(epsg=4326) if gdf.crs is not None else gdf  # Project to WGS84
        centroids = gdf.geometry.centroid  # Centroids
        df_loc = pd.DataFrame({  # Build location table
            "fid": gdf["fid"],  # fid column
            "lon": centroids.x,  # Longitude
            "lat": centroids.y,  # Latitude
            "country": gdf["COUNTRY"] if "COUNTRY" in gdf.columns else "Unknown"  # Country
        })  # DataFrame complete
        log_message(f"Wind turbine centroid coordinates extracted, records: {len(df_loc)}", log_path)  # Record success
        return df_loc  # Return location table
    except Exception as e:  # Centroid computation failed
        log_message(f"Failed to compute centroids: {e}", log_path)  # Record error
        return None  # Return None

# ================= Plotting functions =================

def plot_country_ranking(df, output_dir, log_path=None):  # Country ranking
    log_message("Plotting 1. Country carbon debt ranking...", log_path)  # Record progress
    if "country_final" not in df.columns:  # Check country field
        df["country_final"] = "Unknown"  # Fill with Unknown if absent
    cnt_stats = df.groupby("country_final")["Total_Debt_tCO2"].sum().sort_values(ascending=False).head(20)  # Compute ranking
    cnt_stats_mt = cnt_stats / 1e6  # Convert to MtCO2e
    plt.figure(figsize=(12, 7))  # Figure size
    sns.barplot(x=cnt_stats_mt.values, y=cnt_stats_mt.index, palette="Reds_r")  # Draw bar plot
    plt.title("Top 20 Countries by Wind Carbon Debt (2017+)", fontsize=16, fontweight="bold")  # Title
    plt.xlabel("Total Carbon Debt (MtCO2e)", fontsize=12)  # X axis
    plt.ylabel("")  # Y axis
    for i, v in enumerate(cnt_stats_mt.values):  # Add labels
        plt.text(v + v * 0.01, i, f"{v:.2f}", va="center", fontsize=10)  # Value annotation
    filename = "1_Bar_Country_TotalDebt_2017plus.png"  # Output figure name
    plt.savefig(os.path.join(output_dir, filename))  # Save figure
    plt.close()  # Close figure
    export_plot_data(cnt_stats_mt, filename, output_dir, log_path)  # Export chart data

def plot_annual_trend(df, output_dir, log_path=None):  # Annual trend
    log_message("Plotting 2. Annual carbon debt trend...", log_path)  # Record progress
    trend_df = df[(df["installation_year"] >= START_YEAR) & (df["installation_year"] <= END_YEAR)]  # Filter by year
    yr_stats = trend_df.groupby("installation_year")["Total_Debt_tCO2"].sum() / 1e6  # Aggregate by year
    plt.figure(figsize=(12, 6))  # Figure size
    plt.bar(yr_stats.index, yr_stats.values, color="#d62728", alpha=0.7)  # Bar plot
    plt.title("Annual Wind Carbon Debt (2017-2024)", fontsize=16, fontweight="bold")  # Title
    plt.xlabel("Year", fontsize=12)  # X axis
    plt.ylabel("Annual Carbon Debt (MtCO2e)", fontsize=12)  # Y axis
    plt.grid(axis="y", alpha=0.3)  # Grid
    filename = "2_Bar_Annual_TotalDebt_2017_2024.png"  # Output figure name
    plt.savefig(os.path.join(output_dir, filename))  # Save figure
    plt.close()  # Close figure
    export_plot_data(yr_stats, filename, output_dir, log_path)  # Export chart data

def plot_component_pie(df, output_dir, log_path=None):  # Component contribution pie chart
    log_message("Plotting 3. Carbon debt component contribution...", log_path)  # Record progress
    if "Loss_Bio_tCO2" not in df.columns:  # Check biomass CO2 field
        df["Loss_Bio_tCO2"] = 0  # Set to 0 if missing
    if "Loss_Soil_tCO2" not in df.columns:  # Check soil carbon CO2 field
        df["Loss_Soil_tCO2"] = 0  # Set to 0 if missing
    if "Loss_Mfg_tCO2" not in df.columns:  # Check manufacturing carbon field
        df["Loss_Mfg_tCO2"] = 0  # Set to 0 if missing
    sums = [df["Loss_Bio_tCO2"].sum(), df["Loss_Soil_tCO2"].sum(), df["Loss_Mfg_tCO2"].sum()]  # Compute totals
    labels = ["Biomass CO2e", "Soil CO2e", "Manufacturing CO2e"]  # Labels
    plt.figure(figsize=(8, 8))  # Figure size
    plt.pie(sums, labels=labels, autopct="%1.1f%%", startangle=90, colors=["#d62728", "#8c564b", "#1f77b4"])  # Pie chart
    plt.title("Composition of Wind Carbon Debt (2017+)", fontsize=16, fontweight="bold")  # Title
    filename = "3_Pie_Component_Contribution_2017plus.png"  # Output figure name
    plt.savefig(os.path.join(output_dir, filename))  # Save figure
    plt.close()  # Close figure
    export_plot_data(pd.Series(sums, index=labels), filename, output_dir, log_path)  # Export chart data

def plot_component_trend(df, output_dir, log_path=None):  # Component annual trend
    log_message("Plotting 4. Component annual trend...", log_path)  # Record progress
    trend_df = df[(df["installation_year"] >= START_YEAR) & (df["installation_year"] <= END_YEAR)]  # Filter by year
    comp_df = trend_df.groupby("installation_year")[["Loss_Bio_tCO2", "Loss_Soil_tCO2", "Loss_Mfg_tCO2"]].sum() / 1e6  # Aggregate
    comp_df = comp_df.fillna(0)  # Fill missing with 0
    comp_df.plot(kind="bar", stacked=True, figsize=(12, 6), color=["#d62728", "#8c564b", "#1f77b4"])  # Stacked bar chart
    plt.title("Annual Component Breakdown of Wind Carbon Debt (2017-2024)", fontsize=16, fontweight="bold")  # Title
    plt.xlabel("Year", fontsize=12)  # X axis
    plt.ylabel("Annual Carbon Debt (MtCO2e)", fontsize=12)  # Y axis
    plt.legend(["Biomass CO2e", "Soil CO2e", "Manufacturing CO2e"])  # Legend
    plt.grid(axis="y", alpha=0.3)  # Grid
    filename = "4_Stacked_Annual_Component_2017_2024.png"  # Output figure name
    plt.savefig(os.path.join(output_dir, filename))  # Save figure
    plt.close()  # Close figure
    export_plot_data(comp_df, filename, output_dir, log_path)  # Export chart data

def plot_debt_distribution(df, output_dir, log_path=None):  # Carbon debt distribution
    log_message("Plotting 5. Per-site carbon debt distribution...", log_path)  # Record progress
    plot_df = df[df["Total_Debt_tCO2"] > 0].copy()  # Filter invalid data
    plot_df["Log_Total_Debt"] = np.log10(plot_df["Total_Debt_tCO2"])  # Take logarithm
    plt.figure(figsize=(10, 6))  # Figure size
    sns.histplot(plot_df["Log_Total_Debt"], bins=50, kde=True, color="#d62728")  # Distribution plot
    plt.title("Distribution of Wind Carbon Debt per Site (Log10)", fontsize=16, fontweight="bold")  # Title
    plt.xlabel("Log10(Total Debt tCO2e)", fontsize=12)  # X axis
    plt.ylabel("Count of Wind Sites", fontsize=12)  # Y axis
    filename = "5_Hist_Debt_Distribution_Log10.png"  # Output figure name
    plt.savefig(os.path.join(output_dir, filename))  # Save figure
    plt.close()  # Close figure
    export_plot_data(plot_df["Log_Total_Debt"].describe(), filename, output_dir, log_path)  # Export chart data

def plot_debt_map(df, df_loc, output_dir, log_path=None):  # Carbon debt map distribution
    log_message("Plotting 6. Global carbon debt spatial distribution map...", log_path)  # Record progress
    if df_loc is None:  # If no location data
        log_message("Skipped: missing wind turbine location data; cannot plot the map.", log_path)  # Notice
        return  # Return
    df_m = df.merge(df_loc[["fid", "lon", "lat"]], on="fid", how="left")  # Merge longitude/latitude
    df_m = df_m[df_m["Total_Debt_tCO2"] > 0]  # Filter valid
    df_m = df_m.dropna(subset=["lon", "lat"])  # Drop records without coordinates
    try:  # Try to read world map
        world = gpd.read_file(WORLD_SHP)  # Read world map
    except Exception:  # Set to None on failure
        world = None  # No world map
    fig, ax = plt.subplots(figsize=(15, 8))  # Canvas
    if world is not None:  # Plot base map
        world.plot(ax=ax, color="#f0f0f0", edgecolor="white")  # World base map
    sc = ax.scatter(  # Scatter plot
        df_m["lon"], df_m["lat"],  # Coordinates
        c=df_m["Total_Debt_tCO2"],  # Color by carbon debt
        s=(df_m["Total_Debt_tCO2"] / df_m["Total_Debt_tCO2"].max()) * 50 + 2,  # Point size
        cmap="Reds",  # Color map
        norm=LogNorm(vmin=max(df_m["Total_Debt_tCO2"].quantile(0.05), 1e-6), vmax=df_m["Total_Debt_tCO2"].quantile(0.99)),  # Log color scale
        alpha=0.85,  # Transparency
        edgecolors="none"  # Edges
    )  # End of plotting
    plt.colorbar(sc, label="Total Carbon Debt (tCO2e)", fraction=0.02, pad=0.04)  # Color bar
    plt.title("Global Distribution of Wind Carbon Debt (2017+)", fontsize=16, fontweight="bold")  # Title
    plt.axis("off")  # Turn off axes
    filename = "6_Map_Wind_Carbon_Debt_2017plus.png"  # File name
    plt.savefig(os.path.join(output_dir, filename))  # Save figure
    plt.close()  # Close figure
    export_plot_data(df_m[["fid", "lon", "lat", "Total_Debt_tCO2"]], filename, output_dir, log_path)  # Export data

def plot_latitude_band(df, df_loc, output_dir, log_path=None):  # Latitude band analysis
    log_message("Plotting 7. Latitude band carbon debt statistics...", log_path)  # Record progress
    if df_loc is None:  # If no location data
        log_message("Skipped: missing wind turbine location data; cannot compute latitude bands.", log_path)  # Notice
        return  # Return
    df_m = df.merge(df_loc[["fid", "lat"]], on="fid", how="left")  # Merge latitude
    df_m = df_m.dropna(subset=["lat"])  # Drop records without latitude
    bins = list(range(-60, 95, 5))  # 5-degree bins
    df_m["lat_bin"] = pd.cut(df_m["lat"], bins=bins)  # Bin
    band_stats = df_m.groupby("lat_bin")["Total_Debt_tCO2"].sum() / 1e6  # MtCO2e
    band_stats = band_stats[band_stats > 0]  # Filter empty bins
    plt.figure(figsize=(12, 6))  # Canvas
    sns.barplot(x=band_stats.index.astype(str), y=band_stats.values, color="#d62728")  # Bar plot
    plt.xticks(rotation=90)  # Rotate X axis
    plt.title("Wind Carbon Debt by Latitude Band (2017+)", fontsize=16, fontweight="bold")  # Title
    plt.xlabel("Latitude Band (deg)")  # X axis
    plt.ylabel("Total Carbon Debt (MtCO2e)")  # Y axis
    filename = "7_Bar_Latitude_Band_TotalDebt_2017plus.png"  # Output name
    plt.tight_layout()  # Tight layout
    plt.savefig(os.path.join(output_dir, filename))  # Save figure
    plt.close()  # Close
    export_plot_data(band_stats, filename, output_dir, log_path)  # Export data

def plot_tech_intensity(df, df_mfg, output_dir, log_path=None):  # Technology-carbon intensity relationship plot
    log_message("Plotting 8. Technology-carbon intensity scatter plot...", log_path)  # Record progress
    if df_mfg is None or df_mfg.empty:  # If no manufacturing data
        log_message("Skipped: missing manufacturing carbon data; cannot plot the relationship.", log_path)  # Notice
        return  # Return
    df_p = df_mfg.copy()  # Copy manufacturing data
    df_p["fid"] = pd.to_numeric(df_p["fid"], errors="coerce").astype("Int64")  # Standardize fid
    df_p["Rated_Power_MW"] = pd.to_numeric(df_p.get("Rated_Power_MW", np.nan), errors="coerce")  # Rated power
    df_m = df.merge(df_p[["fid", "Rated_Power_MW"]], on="fid", how="left")  # Merge power
    df_m = df_m.dropna(subset=["Rated_Power_MW"])  # Filter missing
    df_m = df_m[df_m["Rated_Power_MW"] > 0]  # Filter non-positive values
    df_m["Debt_Intensity_tCO2_MW"] = df_m["Total_Debt_tCO2"] / df_m["Rated_Power_MW"]  # Compute intensity
    df_m["BubbleSize"] = (df_m["Total_Debt_tCO2"] / df_m["Total_Debt_tCO2"].max()) * 300 + 10  # Bubble size
    plt.figure(figsize=(12, 8))  # Canvas
    sc = plt.scatter(  # Scatter plot
        df_m["Rated_Power_MW"], df_m["Debt_Intensity_tCO2_MW"],  # Axes: rated power vs intensity
        c=df_m["installation_year"],  # Color by installation year
        s=df_m["BubbleSize"],  # Bubble size
        cmap="viridis",  # Color map
        alpha=0.8,  # Transparency
        edgecolors="k", linewidths=0.2  # Edges
    )  # End of plotting
    plt.colorbar(sc, label="Installation Year")  # Color bar
    plt.title("Rated Power vs Carbon Debt Intensity (2017+)", fontsize=16, fontweight="bold")  # Title
    plt.xlabel("Rated Power per Turbine (MW)")  # X axis
    plt.ylabel("Carbon Debt Intensity (tCO2e/MW)")  # Y axis
    filename = "8_Scatter_RatedPower_vs_DebtIntensity_2017plus.png"  # File name
    plt.savefig(os.path.join(output_dir, filename))  # Save figure
    plt.close()  # Close figure
    export_plot_data(df_m[["fid", "Rated_Power_MW", "Debt_Intensity_tCO2_MW", "installation_year", "Total_Debt_tCO2"]], filename, output_dir, log_path)  # Export data

# ================= Main program =================

def process_scenario(scenario_name):
    """
    Process wind carbon debt statistics for a single scenario
    """
    print(f"\n>>> Processing statistics scenario: {scenario_name}")
    
    # Path setup
    input_csv = os.path.join(BASE_INPUT_DIR, scenario_name, "Wind_Total_Carbon_Debt_Result.csv")
    output_dir = os.path.join(BASE_INPUT_DIR, scenario_name)
    ensure_dir(output_dir)
    log_path = os.path.join(output_dir, "Wind_Debt_Stats_2017plus_Log.txt")
    
    mfg_csv = os.path.join(BASE_MFG_DIR, scenario_name, "Wind_Manufacturing_Carbon_Result.csv")
    
    if os.path.exists(log_path):
        os.remove(log_path)
    
    log_message(f"Scenario: {scenario_name}", log_path)
    log_message(f"Input file: {input_csv}", log_path)

    # Load data
    df = load_data(input_csv, log_path)
    if df is None or df.empty:
        log_message("Data is empty; skipping this scenario.", log_path)
        return

    # Filter by year
    df = df[df["installation_year"] >= START_YEAR].copy()
    log_message(f"Records from 2017 onwards: {len(df)}", log_path)
    
    # Data preprocessing
    df["Total_Debt_tCO2"] = df["Total_Debt_tCO2"].fillna(0)
    total_debt_mt = df["Total_Debt_tCO2"].sum() / 1e6
    log_message(f"Total wind carbon debt (2017+): {total_debt_mt:.4f} MtCO2e", log_path)

    # Plotting
    plot_country_ranking(df, output_dir, log_path)
    plot_annual_trend(df, output_dir, log_path)
    plot_component_pie(df, output_dir, log_path)
    plot_component_trend(df, output_dir, log_path)
    plot_debt_distribution(df, output_dir, log_path)
    
    # Load location data
    df_loc = load_shp_centroids(log_path)
    plot_debt_map(df, df_loc, output_dir, log_path)
    plot_latitude_band(df, df_loc, output_dir, log_path)
    
    # Read manufacturing data for the technology-intensity relationship
    df_mfg = pd.read_csv(mfg_csv) if os.path.exists(mfg_csv) else None
    plot_tech_intensity(df, df_mfg, output_dir, log_path)
    
    log_message("All figures and data generated.", log_path)

def main():
    scenarios = ["乐观场景", "标准场景", "悲观场景"]
    for scenario in scenarios:
        process_scenario(scenario)

if __name__ == "__main__":
    main()
